Overlay support fix

diff --git a/apm b/apm
--- a/apm
+++ b/apm
@@ -66,7 +66,7 @@ down() {
                 axel "$@" || err "apm: an error occured while trying to download"
             ;;
             *)
-                wget "$@" || err "apm: an error occured while trying to download"
+                wget -q --show-progress "$@" || err "apm: an error occured while trying to download"
             ;;
         esac
     else
@@ -154,12 +154,12 @@ build_package() {
     fi
     else
         echo "Which repo will you use"
-        info $1
+        get_info $1
         read WHICH_REPO
 
         # Sourcing the package runfile
         # shellcheck source=/dev/null
-        . "$REPO_PATH"/"$WHICH_REPO"/"$1"/run
+        . "$REPO_PATH"/"$WHICH_REPO-repo"/"$1"/run
 
         # Building the package and making it into a nice tarball
         cd $SRCDIR || exit 1
@@ -212,12 +212,12 @@ install_overlay() {
         cd "$ROOT" || err "apm: unknown error" 
         tar -hxvf "$2" > /tmp/"$1".log
         [ ! -d "$ROOT/$INSTALLED_DIR/$1" ] && mkdir -p "$ROOT/$INSTALLED_DIR/$1"
-        cp -rf "$REPO_PATH/$WHICH_REPO/$1/"* "$ROOT/$INSTALLED_DIR/$1"
+        cp -rf "$REPO_PATH/$WHICH_REPO-repo/$1/"* "$ROOT/$INSTALLED_DIR/$1"
         mv /tmp/"$1".log "$ROOT/$INSTALLED_DIR/$1/list_files"
     else
         tar -xvf "$2" -C /
         [ ! -d "$INSTALLED_DIR/$1" ] && mkdir -p "$INSTALLED_DIR/$1"
-        cp -rf "$REPO_PATH/$WHICH_REPO/$1/"* "$INSTALLED_DIR/$1"
+        cp -rf "$REPO_PATH/$WHICH_REPO-repo/$1/"* "$INSTALLED_DIR/$1"
         mv /tmp/"$1".log "$INSTALLED_DIR/$1/list_files"
     fi
 }
@@ -377,6 +377,7 @@ get_info() {
 	. "$i-repo"/"$1"/run
 	[ -d "$INSTALLED_DIR/$1"] && ISINSTALLED=yes
 	[ ! -d "$INSTALLED_DIR/$1"] && ISINSTALLED=no
+        echo "REPO: $i"
 	echo "package name: $NAME"
 	echo "package desc: $DESCRIPTION"
 	echo "is installed: $ISINSTALLED"
