Added installpackage for overlay packages

diff --git a/apm b/apm
--- a/apm
+++ b/apm
@@ -190,6 +190,21 @@ install_package() {
     fi
 }
 
+install_overlay() {
+    # Install tarball
+    if [ ! "$ROOT" = "" ]; then
+        cd "$ROOT" || err "apm: unknown error" 
+        tar -hxvf "$2" > /tmp/"$1".log
+        [ ! -d "$ROOT/$INSTALLED_DIR/$1" ] && mkdir -p "$ROOT/$INSTALLED_DIR/$1"
+        cp -rf "$i/$1/"* "$ROOT/$INSTALLED_DIR/$1"
+        mv /tmp/"$1".log "$ROOT/$INSTALLED_DIR/$1/list_files"
+    else
+        tar -xvf "$2" -C /
+        [ ! -d "$INSTALLED_DIR/$1" ] && mkdir -p "$INSTALLED_DIR/$1"
+        cp -rf "$i/$1/"* "$INSTALLED_DIR/$1"
+        mv /tmp/"$1".log "$INSTALLED_DIR/$1/list_files"
+    fi
+}
 
 # Install binaries from the repository
 # A feature long-waited, shipped with apm v1.4
